import xml.etree.ElementTree as ET
import msvcrt
import time
import re
import os


APP_NAME = os.path.basename(__file__).replace("_", " ").strip(".py")

class InvalidFileFormat(BaseException): ...

def print_box(lines:list[str], h_padd:int = 4, v_padd:int = 2, alignment:str = "left"):
    """_summary_

    Args:
        lines (list[str]): list of strings to be printed.
        h_padd (int, optional): Horizontal Padding. Defaults to 4.
        v_padd (int, optional): Vertical Padding. Defaults to 2.
        alignment (str, optional): Alignment of lines. Avaliable options are left, right and center.
    """
    max_length = max(len(line) for line in lines)
    
    half_h_padd = " " * int(h_padd/2)
    half_v_padd = int(v_padd/2)

    top_border = "┌" + "─" * (max_length + h_padd) + "┐"
    bottom_border = "└" + "─" * (max_length + h_padd) + "┘"

    print(top_border)
    for _ in range(0, half_v_padd):
        print(f"│{" " * (max_length + h_padd)}│")
    
    for line in lines:
        line = (line.ljust(max_length) if alignment == "left" else line.rjust(max_length) if alignment == "right" else line.center(max_length))
        print(f"│{half_h_padd}{line}{half_h_padd}│")
    
    for _ in range(0, half_v_padd):
        print(f"│{" " * (max_length + h_padd)}│")
    print(bottom_border)

def quote_unicode(s: str):
    if not s:
        return s
    
    if s.startswith('"') and s.endswith('"'):
        s = s[1:-1]
    
    # s = s.replace("\\", "\\\\")  # Backslash must be first
    # s = s.replace("\"", "\\\"")  # Double quote
    # s = s.replace("\'", "\\'")   # Single quote
    s = s.replace("\a", "\\a")   # Bell
    s = s.replace("\b", "\\b")   # Backspace
    s = s.replace("\f", "\\f")   # Form feed
    s = s.replace("\n", "\\n")   # Newline
    s = s.replace("\r", "\\r")   # Carriage return
    s = s.replace("\t", "\\t")   # Tab
    s = s.replace("\v", "\\v")   # Vertical tab
    s = s.replace("\0", "\\0")   # Null character
    
    return s

def unquote_unicode(s: str):
    if not s:
        return s
    
    s = s.replace("\\a", "\a")
    s = s.replace("\\b", "\b")
    s = s.replace("\\f", "\f")
    s = s.replace("\\n", "\n")
    s = s.replace("\\r", "\r")
    s = s.replace("\\t", "\t")
    s = s.replace("\\v", "\v")
    s = s.replace("\\0", "\0")
    # s = s.replace("\\\"", "\"")
    # s = s.replace("\\'", "'")
    # s = s.replace("\\\\", "\\")
    
    if "  " in s or "'" in s or "\n" in s or "\r" in s or "\t" in s or s[0] == " " or s[-1] == " ":
        s = f'"{s}"'
        
    if s[0] == "?":
        s = f"\\{s}"
    
    return s

def get_xml_strings(file_path: str):
    tree = ET.parse(file_path)
    root = tree.getroot()
    strings = {}
    
    for child in root.iter("string"):
        name = child.get("name", None)
        if name:
            text = child.text
            strings.setdefault(name, text)
    
    return strings

def export_strings(filename: str, strings: dict):
    try:
        exported_strings_count = 0
        filename = f"{filename}.strings"
        with open(filename, "w", encoding="utf-8") as f:
            f.write(f"/* Generated by veydzh3r's {APP_NAME} */\n")
            for name in sorted(strings):
                if strings[name] is not None:
                    text = quote_unicode(strings[name])
                    f.write(f"\"{name}\" = \"{text}\";\n")
                    exported_strings_count += 1
                else:
                    f.write(f"\"{name}\" = \"\";\n")
    except Exception as e:
        print(f"Export error: {str(e)}")
        return False
    
    print_box([f"Exported strings: {exported_strings_count}", f"{filename} created successfully!"])
    return True

def get_apple_strings(file_path: str):
    try:
        try:
            with open(file_path, "r", encoding="utf-16") as f:
                content = f.read()
        except UnicodeError:
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()
    except Exception as e:
        print(f"Error reading file {file_path}: {e}")
        return {}

    content = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
    content = re.sub(r'//.*', '', content)

    pattern = r'"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;'
    matches = re.findall(pattern, content, flags=re.DOTALL)

    result = {}
    for key, value in matches:
        unescaped_key = unquote_unicode(key)
        unescaped_value = unquote_unicode(value)
        result[unescaped_key] = unescaped_value

    return result

def import_strings(source_file: str, output_file: str, strings: dict):
    try:
        tree = ET.parse(source_file)
        root = tree.getroot()
        import_strings_count = 0
        
        for str_obj in root.iter("string"):
            obj_name = str_obj.get("name")
            if obj_name in strings and obj_name:
                old_text = str_obj.text # type: ignore
                new_text = strings[obj_name]
                if old_text != new_text and str_obj.text is not None:
                    print(f"Changed: {obj_name}")
                    print(f"  From: {repr(str_obj.text)}")
                    print(f"  To:   {repr(new_text)}")
                    str_obj.text = new_text
                    
                    if str_obj.tail and str_obj.tail.strip() == "":
                        str_obj.tail = str_obj.tail
                    else:
                        str_obj.tail = "\n    "
                    
                    import_strings_count += 1

        if import_strings_count != 0:
            tree.write(f"{output_file}.xml", encoding="utf-8", xml_declaration=True)
            print_box([f"Imported strings: {import_strings_count}", f"{output_file}.xml created successfully!"])
            print()
        else:
            print("Found no strings to update!")
        
    except Exception as e:
        print(f"Import error: {e}")

def clear():
    os.system('cls' if os.name == 'nt' else 'clear')

def main():
    print_box(["XML to STRINGS Converter Program by veydzh3r", "Github: https://github.com/Veydzher/Translation-Tools"], 6, 2, "center")
    try:
        choice = int(input("1. Export strings from .xml\n2. Import strings from .strings\n3. Exit the program\n\n>>> "))
        
        if choice == 1:
            xml_file_path = input("Enter the path to a .xml file: ").strip().strip('"')
            if not xml_file_path or not os.path.exists(xml_file_path):
                raise FileNotFoundError("Specified .xml file not found! Try again.")
            elif not xml_file_path.endswith(".xml"):
                raise InvalidFileFormat("Invalid file format! Should be .xml!")
        
            output_file = input("Enter a name of .strings output file (default: Localizable): ").strip()
            if not output_file:
                output_file = "Localizable"
                
            print()
                
            strings = get_xml_strings(xml_file_path)
            if strings:
                export_strings(output_file, strings)
            else:
                print("No strings found in XML file!")
                
        elif choice == 2:
            xml_file_path = input("Enter the path to a XML file: ").strip().strip('"')
            if not xml_file_path or not os.path.exists(xml_file_path):
                raise FileNotFoundError("Specified .xml file not found! Try again.")
            elif not xml_file_path.endswith(".xml"):
                raise InvalidFileFormat("Invalid file format! Should be .xml!")
        
            apple_file_path = input("Enter the path to a .strings file: ").strip().strip('"')
            if not apple_file_path or not os.path.exists(apple_file_path):
                raise FileNotFoundError("Specified .strings file not found! Try again.")
            elif not apple_file_path.endswith(".strings"):
                raise InvalidFileFormat("Invalid file format! Should be .strings!")
            
            output_file = input("Enter a name of .xml output file (default: strings_edited): ").strip()
            if not output_file:
                output_file = "strings_edited"
                
            print()
            
            modified_strings = get_apple_strings(apple_file_path)
            if modified_strings:
                import_strings(xml_file_path, output_file, modified_strings)
                print(f"Processed {len(modified_strings)} strings from .strings file")
            else:
                print("No valid strings found in .strings file!")
        
        elif choice == 3:
            print("Exiting the program...")
            exit(0)
        
        elif choice not in [1,2,3]:
            raise ValueError
        
        print("Press any key to exit main menu..."); msvcrt.getch(); main()
            
    except ValueError:
        print("Invalid input. Try again."); time.sleep(1); clear(); main()
    except FileNotFoundError as e:
        print(str(e)); time.sleep(1); clear(); main()
    except InvalidFileFormat as e:
        print(str(e)); time.sleep(1); clear(); main()
    except KeyboardInterrupt:
        print("\n\nProgram interrupted by user."); exit(0)
    except Exception as e:
        print(f"Unexpected error: {str(e)}\n\nReport the error to veydzh3r.")

if __name__ == "__main__":
    main()
